export const exampleNodeDefinitions = [
  { id: "start" },
  { id: "expectations" },
  { id: "name" },
  { id: "dob" },
  { id: "address" },
  { id: "ageCheck" },
  { id: "employment" },
  { id: "housing" },
  { id: "income" },
  { id: "householdIncome" },
  { id: "review" },
  { id: "checks" },
  { id: "pin" },
  { id: "pinEnd" },
  { id: "ageDecline" },
  { id: "ageDeclineEnd" },
];

export const exampleEdgeDefinitions = [
  { source: "start", target: "expectations" },
  { source: "expectations", target: "name" },
  { source: "name", target: "dob" },
  { source: "dob", target: "address" },
  { source: "address", target: "ageCheck" },
  { source: "ageCheck", target: "employment", label: "Continue" },
  { source: "ageCheck", target: "ageDecline", label: "Decline" },
  { source: "ageDecline", target: "ageDeclineEnd" },
  { source: "employment", target: "housing" },
  { source: "housing", target: "income" },
  { source: "income", target: "householdIncome" },
  { source: "householdIncome", target: "review" },
  { source: "review", target: "checks" },
  { source: "checks", target: "pin" },
  { source: "pin", target: "pinEnd" },
];

export const exampleInputText = `
const nodes = [
  new StartNode('start'),
  new ExpectationNode('expectationAboutYourself', {
    currentStep: ExpectationScreenStep.ABOUT_YOURSELF,
    availableSteps: [
      ExpectationScreenStep.ABOUT_YOURSELF,
      ExpectationScreenStep.VERIFY_IDENTITY,
      ExpectationScreenStep.SETUP_CARD,
    ],
  }),
  new NameNode('name'),
  new DobNode('dob'),
  new AddressNode('address'),
  new EmploymentNode('employment'),
  new AgeCheckNode('ageCheck'),
  new DeclineNode('ageCheckDecline', { declineReason: DeclineReason.AGE }, this.applicationRepository),
  new HousingNode('housing'),
  new IncomeNode('income', this.annualIncomeStorageEncryption),
  new HouseholdIncomeNode('householdIncome', this.annualHouseholdIncomeStorageEncryption),
  new InformationReviewNode('informationReview'),
  new PrimaryChecksNode(
    'primaryChecks',
    this.primaryChecksRequestedProducer,
    this.applicationRepository,
    this.applicationConfigRepository,
    this.annualIncomeStorageEncryption,
    this.annualIncomeTransportEncryption,
    this.annualHouseholdIncomeStorageEncryption,
    this.annualHouseholdIncomeTransportEncryption,
    {
      checksToRun: [
        Check.KYC_CHECK,
        Check.TRANSUNION_SOFT_CREDIT_CHECK,
        Check.TRANSUNION_EBVS_ID_CHECK,
        Check.IOVATION_DIGITAL_FRAUD_CHECK,
        Check.ENSTREAM_ACCOUNT_INTEGRITY_CHECK,
        Check.ENSTREAM_IDENTITY_VERIFICATION_CHECK,
        Check.ADJUDICATION_CHECK,
        Check.FRAUD_VENDOR_CHECK,
        Check.AML_SCREENING_CHECK,
      ],
    },
  ),
  new PinNode('pin'),
  new EndNode('end'),
];
const edges = [
  new Edge({
    sourceNodeId: 'start',
    sourcePinId: 'outputNavigationPin',
    targetNodeId: 'expectationAboutYourself',
    targetPinId: 'inputNavigationPin',
  }),
  new Edge({
    sourceNodeId: 'expectationAboutYourself',
    sourcePinId: 'outputNavigationPin',
    targetNodeId: 'name',
    targetPinId: 'inputNavigationPin',
  }),
  new Edge({
    sourceNodeId: 'name',
    sourcePinId: 'outputNavigationPin',
    targetNodeId: 'dob',
    targetPinId: 'inputNavigationPin',
  }),
  new Edge({
    sourceNodeId: 'dob',
    sourcePinId: 'outputNavigationPin',
    targetNodeId: 'address',
    targetPinId: 'inputNavigationPin',
  }),
  new Edge({
    sourceNodeId: 'address',
    sourcePinId: 'outputNavigationPin',
    targetNodeId: 'ageCheck',
    targetPinId: 'inputNavigationPin',
  }),
  new Edge({
    sourceNodeId: 'ageCheck',
    sourcePinId: 'outputNavigationPinContinue',
    targetNodeId: 'employment',
    targetPinId: 'inputNavigationPin',
  }),
  new Edge({
    sourceNodeId: 'ageCheck',
    sourcePinId: 'outputNavigationPinDecline',
    targetNodeId: 'ageCheckDecline',
    targetPinId: 'inputNavigationPin',
  }),
  new Edge({
    sourceNodeId: 'ageCheckDecline',
    sourcePinId: 'outputNavigationPin',
    targetNodeId: 'end',
    targetPinId: 'inputNavigationPin',
  }),
  new Edge({
    sourceNodeId: 'employment',
    sourcePinId: 'outputNavigationPin',
    targetNodeId: 'housing',
    targetPinId: 'inputNavigationPin',
  }),
  new Edge({
    sourceNodeId: 'housing',
    sourcePinId: 'outputNavigationPin',
    targetNodeId: 'income',
    targetPinId: 'inputNavigationPin',
  }),
  new Edge({
    sourceNodeId: 'income',
    sourcePinId: 'outputNavigationPin',
    targetNodeId: 'householdIncome',
    targetPinId: 'inputNavigationPin',
  }),
  new Edge({
    sourceNodeId: 'householdIncome',
    sourcePinId: 'outputNavigationPin',
    targetNodeId: 'informationReview',
    targetPinId: 'inputNavigationPin',
  }),
  new Edge({
    sourceNodeId: 'informationReview',
    sourcePinId: 'outputNavigationPin',
    targetNodeId: 'primaryChecks',
    targetPinId: 'inputNavigationPin',
  }),
  new Edge({
    sourceNodeId: 'primaryChecks',
    sourcePinId: 'outputNavigationPin',
    targetNodeId: 'pin',
    targetPinId: 'inputNavigationPin',
  }),
  new Edge({
    sourceNodeId: 'pin',
    sourcePinId: 'outputNavigationPin',
    targetNodeId: 'end',
    targetPinId: 'inputNavigationPin',
  }),
];
`;
